version: '3.0'

services:
  grafana:
    container_name: 'slack-astra-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.3.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/slack-astra-app
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_LOG_MODE: "console file"
      GF_LOG_LEVEL: "debug"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PLUGINS: "/var/lib/grafana/plugins"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "slack-astra-app,slack-astra-app-backend-datasource"
      GF_SERVER_ENABLE_GZIP: "true"
