version: "3"
services:
  grafana:
    image: 'grafana/grafana:8.0.3'
    container_name: slack_kaldb_app_grafana
    ports:
      - '3000:3000'
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./:/var/lib/grafana/plugins/slack-kaldb-app
    environment:
      GF_LOG_MODE: "console file"
      GF_LOG_LEVEL: "debug"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PLUGINS: "/var/lib/grafana/plugins"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "slack-kaldb-app,slack-kaldb-app-backend-datasource"
