version: '3.0'

services:
  grafana:
    container_name: 'slack-kaldb-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/slack-kaldb-app
      - ./provisioning:/etc/grafana/provisioning
      - ./conf/:/var/lib/grafana/conf
    environment:
      GF_LOG_MODE: "console file"
      GF_LOG_LEVEL: "debug"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PLUGINS: "/var/lib/grafana/plugins"
      GF_PATHS_CONFIG: "/var/lib/grafana/conf/custom.ini"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "slack-kaldb-app,slack-kaldb-app-backend-datasource"
